name: swiftgift_app
description: 'SwiftGift App'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.6.0
  google_sign_in: ^6.2.1
  flutter_dotenv: ^5.1.0
  http: ^1.2.1
  sign_in_button: ^3.2.0
  share_plus: ^10.0.3
  flutter_speed_dial: ^7.0.0
  smooth_page_indicator: ^1.2.0+3
  image_picker: ^1.1.2
  path: ^1.9.0
  mime: ^1.0.6
  http_parser: ^4.0.2
  path_provider: ^2.1.4
  sign_in_with_apple: ^6.1.3
  shared_preferences: ^2.3.2
  flutter_otp_text_field: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/gift-background.png
